"""InitialCheck

Revision ID: d3ae64225c24
Revises: 
Create Date: 2023-03-28 11:00:11.589680

"""
import os

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd3ae64225c24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invite_message', 'chanel_name')
    op.drop_column('invite_message', 'chanel_id')
    op.add_column('users', sa.Column('bot_token', sa.VARCHAR(length=200), nullable=False,
                                     server_default='5618506298:AAHqG6APc3Q2T_DVpvmfYtr2xreNsz-YjMQ'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bot_token')
    op.add_column('invite_message', sa.Column('chanel_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('invite_message',
                  sa.Column('chanel_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
